### PR TITLE
Fix STM32F1

### PR DESCRIPTION
**Pull request by WereCatf**
This fixes the STM32F1 - portion of the code, both with and without DMA.

### CODE REVIEW

**Comment by greiman** [comment]
Did you test it? 

It only works for some SPI speeds and almost never unless SPI transactions are enabled.

It often fails for large many block transfers.  It just fails too much of my test suite.

I don't think it is worth my time to follow up.  The STM32 Arduino people have their version of SdFat.

I love STM32 but use the Chibios/RT RTOS since it supports modern fancy STM32 boards.

**Comment by WereCatf** [comment]
Yes, you are right: I did mess it up some. Instead of closing the pull-request you could have just mentioned the issues and let me fix them; I did fix them and I, at least, can't make any of the sketches break now, but I suppose I won't bother making another pull-request then.

**Comment by greiman** [comment]
I fetched your file but there are still problems.  I don't think this is your bug.

After I closed the pull I tried a version that I wrote and it has problems also.

I was testing with SPI transactions enabled at full speed with 32 KiB transfers and all was well.  

Great speed:

>Buffer size 32768 bytes

>write speed and latency
speed,max,min,avg
KB/Sec,usec,usec,usec
3296.32,13298,9148,9929

>read speed and latency
speed,max,min,avg
KB/Sec,usec,usec,usec
3259.64,10410,10034,10052

Then I change the divisor to four, half speed.

>Buffer size 32768 bytes

>write speed and latency
speed,max,min,avg
KB/Sec,usec,usec,usec
error: write failed
SD errorCode: 0X13,0XCA

I tried with SPI transactions disabled and it happens with my version and your version.

Maybe I will try another board.  I think I have an OLIMEXINO-STM32 Maple.  I stopped using STM32F1 years ago.  I now am developing with STM32F7 and some STM352F4.

It could be a bug in the SPI library. 
 
I had a similar problem with the Particle Photon, also a STM32, it was a bug in Particle's SPI library.  The problem was quick back to back DMA transfers failed if the clock was slow since the DMA controller was still busy when the second transfer started.

**Comment by WereCatf** [comment]
Ohh, my device only has 20KB RAM so I wouldn't even be able to test with such large buffers; I had no way of knowing of such an issue.

Interestingly, writing 65KB DMA-transfers to the ILI9341 display works fine, even if you were doing multiple back-to-back transfers, but I have only tested it in circular mode, ie. the source address is never increased and it keeps writing the same byte over and over until it reaches 65k bytes written. Maybe the issue lies with source-addressing somehow?

**Comment by greiman** [comment]
I am finding more problems.  The bench example fails with a divisor of 4 with a buffer size of 1024.  It only fails for high end cards.  Often the bench example writes hundreds of blocks before failure.

The bench example works for divisors other than 4.

The format program fails for fast cards with a divisor of 4.

I found another STM32F103RBT6 board and will try it.  I will search for the Maple card in junk boxes next.

Unfortunately STM32 Arduino does not conform to the Serial spec for returning a negative value when no data is available.  For a while Teensy had a bug in Serial.available() so many examples uses this feature and don't work with STM32.

**Comment by WereCatf** [comment]
> The format program fails for fast cards with a divisor of 4.
This one was a bit unclear to me: does it fail on both high-end and lower-end devices, or just high-end ones?

I only have an STM32F103C, which is classed as a "medium-density" device, so I can't test these things, but I could ask around on the STM32duino - forums if others are experiencing similar issues. If the code works fine on lower-end devices, but fails on the higher-end devices then there is clearly a problem with the SPI-library and someone with access to the hardware should, hopefully, see about fixing it.

I didn't even mean to bother you with this stuff; I just, perhaps foolishly, assumed that if the code works on my device it'd work on all STM32F1 - devices. I totally understand if you have better things to do with your time.

**Comment by greiman** [comment]
Looks like the first STM32F103RBT6 board is bad.

The second STM32F103RBT6 board works with the examples that previously failed. 

I swapped SD sockets and power supplies and the problem stayed with the first board.

I bought the boards a long time ago but followed my rule of buy at least two of anything you use to test with.

What an ugly hardware fault.  I looked at errata for the part but found nothing.

I think your file is OK but I want to change the divisor stuff a bit. I will clean up the version of the file I did, run more tests then post it if all is well.

Just a note about large transfers on SD cards.  A multiple block transfer is a series of 512 byte SPI transfers but you prep the card with special commands.  The card then buffers the data in RAM and finally write a very large, 16-32 KB, flash page.  If you use single block commands it is much slower since the card copies data from one of these large internal pages and adds the extra 512 bytes to another page and writes a new large flash block.  This can increase the internal data movement by as much as a factor of 100.  This can reduce a 40 MB/sec SanDisk Extreme card to few hundred KB/sec on a small Arduino.

**Comment by WereCatf** [comment]
That is indeed a very unexpected failure! It's great that you located the issue before you wasted much more time on it, though.

I will take a look at the changes you make, maybe I'll be able to pick up some insight for future use myself from it -- you can probably tell I am still learning as I go. Anyways, thanks for looking into this (too) :)

**Comment by greiman** [comment]
I posted the STM32F1 changes.  

I modified most examples and did a lot of testing.  

There could still be bugs since I touched so many examples.

**Comment by WereCatf** [comment]
You know, the reason my code checks whether the SPI-device is running on the internal bus APB2 or APB1 is because APB1 runs at half the clock-speed of APB2: your code calculates the divisor based on F_CPU, I would assume, but if the user has set SPI to use SPI-bus 2 with SPI.setModule(2) your code calculates the divisor wrong. On SPI-bus 1 SPI_CLOCK_DIV4 is 18MHz, on SPI-bus 2 SPI_CLOCK_DIV4 is 9MHz, and this is why I use the lower divisor if the bus is APB1 -- if the user has requested half-speed, ie. a 18MHz frequency, then it should be 18MHz frequency regardless of the bus that's in use.

**Comment by greiman** [comment]
> your code calculates the divisor wrong.

No!  The SdFat begin call has a divisor argument, not a frequency argument. 

It should follow SPI.setClockDivider.  That's why I changed your code.

The STM32 Arduino definition of SPI_CLOCK_DIV2 does not depend on the APB1/APB2 frequency. 
````
//  Here is the code that finally returns a zero for the Baud rate control field in SPI_CR1
#define SPI_CLOCK_DIV2   SPI_BAUD_PCLK_DIV_2
SPI_BAUD_PCLK_DIV_2   = SPI_CR1_BR_PCLK_DIV_2,   /**< f_PCLK/2 */
#define SPI_CR1_BR_PCLK_DIV_2           (0x0 << 3)
````
Your code also only allowed powers of two but many apps have other divisors because of boards like Due and Teensy.  You should find the closest  divisor to the provided argument.   Look at how the divisor is determined for SPISettings.

It also is possible that a system would use frequencies other than 72/36 MHz.  Even the STM32F1 has a complex clock tree.

**Comment by WereCatf** [comment]
Take a look at the function determine_baud_rate(spi_dev *dev, uint32_t freq) in https://github.com/rogerclarkmelbourne/Arduino_STM32/blob/master/STM32F1/libraries/SPI/src/SPI.cpp, for example:
If you want to set a frequency of 9MHz it gives a clock-div of SPI_BAUD_PCLK_DIV_8 for APB2, and SPI_BAUD_PCLK_DIV_4 for APB1, so yes: it is dependant on which internal bus the SPI-device is using.

**Comment by WereCatf** [comment]
Maybe I'm just missing something obvious then, but no matter how I read that function I keep getting different divisors for the same requested frequency, depending on the bus.

**Comment by greiman** [comment]
> Maybe I'm just missing something obvious then, but no matter how I read that function I keep getting different divisors for the same requested frequency, depending on the bus.

I wanted you to look at the function because it does not use a case statement to determine the divisor.  Sorry I was not more clear.

The point is that a case statement is not a good way to determine the correct power of two divisor.

Again, SdFat begin() has a divisor argument not a frequency argument.

Even if I wanted to do what you tried to do I wouldn't use your code since your code doesn't work as  you intended.

First, you use  clk_id and assume the bus frequency.  The bus frequency is STM32_PCLK1 or STM32_PCLK2.

Note this:
````
/*
 * MCU-specific values.
 *
 * You can use this section to override any of the below settings on a
 * per-MCU basis. For example, if your MCU has different STM32_PCLK1
 * or STM32_PCLK2 values, you can set them here and the values for
 * STM32F103 microcontrollers set below won't take effect.
 */
````
You don't listen.  I warned you about this above.

Given that the user can use the PLL and prescalers to adjust PCLCK1 and PCLK2, your code is trash.

Once again I don't want a switch statement on divisor.  I want the power of two that is closest and is >=  to the provided divisor argument.

**Comment by WereCatf** [comment]
But I wasn't even telling you to use a case-statement! I only talked about the divisor itself. You're attacking me for something I didn't tell you to do o_o

Nevermind, your code works and I agree that using the if-statement is better than what I did and I hadn't considered that one can adjust those clocks themselves, too, and that I am an awful person and incompetent. I'll drop the topic and move on. Thank you, anyway, for the fix.

**Pull request closed without merging**
